# Part C: Check the processed files

This notebook compares the original files with the saved files.

**Raw** means original. **Processed** means the copy saved by your Python script.

Your current script does not remove rows or fill missing values. We therefore expect the tables to contain the same information. Customer ZIP-code prefixes should keep their leading zeros.

Run one cell at a time with **Shift + Enter**, starting at the top. Read the explanation and output before moving on. A result of `True` means the comparison matched. `False` means you need to investigate.

Open this notebook from the project's `notebooks` folder. The paths beginning with `../` go up to the project folder.

## 1. Load the tools

`pandas` reads and checks tables. We use the short name `pd`.

`Path` lets us read a file's original contents when checking that it stays unchanged.

In [1]:
import pandas as pd
from pathlib import Path

## 2. Remember the original files before processing

These variables hold the exact file contents before the script runs. `read_bytes()` reads the file as stored on disk.

We will compare these contents after processing. This checks this run only; it cannot tell us whether a raw file was changed earlier.

In [2]:
orders_file_before = Path("../data/raw/olist_orders_dataset.csv").read_bytes()
customers_file_before = Path("../data/raw/olist_customers_dataset.csv").read_bytes()
order_items_file_before = Path("../data/raw/olist_order_items_dataset.csv").read_bytes()
products_file_before = Path("../data/raw/olist_products_dataset.csv").read_bytes()
order_reviews_file_before = Path("../data/raw/olist_order_reviews_dataset.csv").read_bytes()

## 3. Run the processing script

`%run` is a notebook command that runs a Python file.

**This cell replaces the five saved CSVs in `data/processed/` with fresh outputs.** The script should leave the raw files unchanged.

In [3]:
%run ../src/process_olist_data.py

Processing dataset: orders

Saved data\processed\orders.csv: 99,441 rows, 8 columns
Processing dataset: customers

Saved data\processed\customers.csv: 99,441 rows, 5 columns
Processing dataset: order_items

Saved data\processed\order_items.csv: 112,650 rows, 7 columns
Processing dataset: products

Saved data\processed\products.csv: 32,951 rows, 9 columns
Processing dataset: order_reviews

Saved data\processed\order_reviews.csv: 99,224 rows, 7 columns
Finished processing all 5 datasets.

## 4. Did the raw files stay unchanged?

`==` means "is equal to". Each line compares a raw file now with the contents remembered before the script ran.

Every result should be `True`. A `False` means that raw file changed during this run.

In [4]:
print("orders unchanged:", orders_file_before == Path("../data/raw/olist_orders_dataset.csv").read_bytes())
print("customers unchanged:", customers_file_before == Path("../data/raw/olist_customers_dataset.csv").read_bytes())
print("order_items unchanged:", order_items_file_before == Path("../data/raw/olist_order_items_dataset.csv").read_bytes())
print("products unchanged:", products_file_before == Path("../data/raw/olist_products_dataset.csv").read_bytes())
print("order_reviews unchanged:", order_reviews_file_before == Path("../data/raw/olist_order_reviews_dataset.csv").read_bytes())

orders unchanged: True
customers unchanged: True
order_items unchanged: True
products unchanged: True
order_reviews unchanged: True

## Check the orders table

### Read both files

`orders_raw` holds the original table. `orders_saved` holds the saved table.

If this cell finishes without an error, Pandas could read both files.

In [5]:
orders_raw = pd.read_csv("../data/raw/olist_orders_dataset.csv")
orders_saved = pd.read_csv("../data/processed/orders.csv")
print("Both files loaded successfully.")

Both files loaded successfully.

### Check the size

`shape` shows `(rows, columns)`. The sizes should match because the script does not remove rows or columns.

In [6]:
print("Raw size:", orders_raw.shape)
print("Saved size:", orders_saved.shape)
print("Same size:", orders_raw.shape == orders_saved.shape)

Raw size: (99441, 8)
Saved size: (99441, 8)
Same size: True

### Check the column names

`columns` lists the column names. `equals()` checks whether both lists match, including their order. Expect `True`.

In [7]:
print("Raw columns:", orders_raw.columns.tolist())
print("Saved columns:", orders_saved.columns.tolist())
print("Same columns:", orders_raw.columns.equals(orders_saved.columns))

Raw columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Saved columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Same columns: True

### Check the data types

`dtypes` shows how Pandas stores each column. Text is shown as `str`, `string`, or `object`; whole numbers as `int64`; decimal numbers as `float64`.

The columns should have the same types in both tables. Matching types does not prove they suit every task: date text would need conversion before date calculations.

In [8]:
print("Raw types:")
print(orders_raw.dtypes)
print("Saved types:")
print(orders_saved.dtypes)
print("Same types:", orders_raw.dtypes.equals(orders_saved.dtypes))

Raw types:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object
Saved types:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object
Same types: True

### Check missing values

`isna().sum()` counts missing values in each column. The counts should stay the same because the script does not fill or remove missing values.

In [9]:
print("Raw missing values:")
print(orders_raw.isna().sum())
print("Saved missing values:")
print(orders_saved.isna().sum())
print("Same missing counts:", orders_raw.isna().sum().equals(orders_saved.isna().sum()))

Raw missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
Saved missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
Same missing counts: True

### Check duplicate rows

`duplicated().sum()` counts repeated complete rows. Repeated IDs alone are a different check.

The counts should stay the same. We have not decided to remove duplicates from these tables.

In [10]:
print("Raw duplicates:", orders_raw.duplicated().sum())
print("Saved duplicates:", orders_saved.duplicated().sum())
print("Same duplicate count:", orders_raw.duplicated().sum() == orders_saved.duplicated().sum())

Raw duplicates: 0

Saved duplicates: 0

Same duplicate count: True

### Check categories and distinct values

`nunique()` counts different non-missing values in each column. These counts should match.

We also inspect `order_status`. `value_counts(dropna=False)` counts each value, including missing values. The comparison checks the complete counts; the next cell displays at most ten values.

In [11]:
print("Same distinct counts:", orders_raw.nunique().equals(orders_saved.nunique()))
orders_raw_counts = orders_raw["order_status"].value_counts(dropna=False)
orders_saved_counts = orders_saved["order_status"].value_counts(dropna=False)
print("Same category counts:", orders_raw_counts.equals(orders_saved_counts))

Same distinct counts: True
Same category counts: True

In [12]:
orders_saved_counts.head(10)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

### Look at sample records

The next two cells display the first five rows of each version separately. Compare them: do their IDs, values, and missing entries match?

A sample helps you understand the data but does not check every row.

In [13]:
orders_raw.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [14]:
orders_saved.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

### Compare the whole table

The following check compares every row and column. Tiny decimal differences caused by saving and rereading CSV files are allowed; text must match.

`pd.testing.assert_frame_equal()` raises an error if the tables differ unexpectedly. If it passes, the success message appears.

In [15]:
pd.testing.assert_frame_equal(orders_raw, orders_saved, check_exact=False, rtol=0.000000000001, atol=0.000000000001)
print("Passed: all table values match within the small decimal tolerance.")

Passed: all table values match within the small decimal tolerance.

### Your notes for orders

After reading the results, edit this Markdown cell in your own words:

- Raw and saved row/column counts:
- Missing values or duplicates noticed:
- What the sample rows show:
- Anything that needs more investigation:

Do not write "no issues" just because the files match. The original data may still contain issues.

## Check the customers table

### Read both files

`customers_raw` holds the original table. `customers_saved` holds the saved table.

If this cell finishes without an error, Pandas could read both files.

ZIP-code prefixes are labels, not amounts. `dtype={"customer_zip_code_prefix": "string"}` tells Pandas to keep them as text. For example, `09790` should keep its first zero. Use the same setting for both files.

In [16]:
customers_raw = pd.read_csv("../data/raw/olist_customers_dataset.csv", dtype={"customer_zip_code_prefix": "string"})
customers_saved = pd.read_csv("../data/processed/customers.csv", dtype={"customer_zip_code_prefix": "string"})
print("Both files loaded successfully.")

Both files loaded successfully.

### Check the size

`shape` shows `(rows, columns)`. The sizes should match because the script does not remove rows or columns.

In [17]:
print("Raw size:", customers_raw.shape)
print("Saved size:", customers_saved.shape)
print("Same size:", customers_raw.shape == customers_saved.shape)

Raw size: (99441, 5)
Saved size: (99441, 5)
Same size: True

### Check the column names

`columns` lists the column names. `equals()` checks whether both lists match, including their order. Expect `True`.

In [18]:
print("Raw columns:", customers_raw.columns.tolist())
print("Saved columns:", customers_saved.columns.tolist())
print("Same columns:", customers_raw.columns.equals(customers_saved.columns))

Raw columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
Saved columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
Same columns: True

### Check the data types

`dtypes` shows how Pandas stores each column. Text is shown as `str`, `string`, or `object`; whole numbers as `int64`; decimal numbers as `float64`.

The columns should have the same types in both tables. Matching types does not prove they suit every task: date text would need conversion before date calculations.

In [19]:
print("Raw types:")
print(customers_raw.dtypes)
print("Saved types:")
print(customers_saved.dtypes)
print("Same types:", customers_raw.dtypes.equals(customers_saved.dtypes))

Raw types:
customer_id                    str
customer_unique_id             str
customer_zip_code_prefix    string
customer_city                  str
customer_state                 str
dtype: object
Saved types:
customer_id                    str
customer_unique_id             str
customer_zip_code_prefix    string
customer_city                  str
customer_state                 str
dtype: object
Same types: True

### Check missing values

`isna().sum()` counts missing values in each column. The counts should stay the same because the script does not fill or remove missing values.

In [20]:
print("Raw missing values:")
print(customers_raw.isna().sum())
print("Saved missing values:")
print(customers_saved.isna().sum())
print("Same missing counts:", customers_raw.isna().sum().equals(customers_saved.isna().sum()))

Raw missing values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
Saved missing values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
Same missing counts: True

### Check duplicate rows

`duplicated().sum()` counts repeated complete rows. Repeated IDs alone are a different check.

The counts should stay the same. We have not decided to remove duplicates from these tables.

In [21]:
print("Raw duplicates:", customers_raw.duplicated().sum())
print("Saved duplicates:", customers_saved.duplicated().sum())
print("Same duplicate count:", customers_raw.duplicated().sum() == customers_saved.duplicated().sum())

Raw duplicates: 0

Saved duplicates: 0

Same duplicate count: True

### Check categories and distinct values

`nunique()` counts different non-missing values in each column. These counts should match.

We also inspect `customer_state`. `value_counts(dropna=False)` counts each value, including missing values. The comparison checks the complete counts; the next cell displays at most ten values.

In [22]:
print("Same distinct counts:", customers_raw.nunique().equals(customers_saved.nunique()))
customers_raw_counts = customers_raw["customer_state"].value_counts(dropna=False)
customers_saved_counts = customers_saved["customer_state"].value_counts(dropna=False)
print("Same category counts:", customers_raw_counts.equals(customers_saved_counts))

Same distinct counts: True
Same category counts: True

In [23]:
customers_saved_counts.head(10)

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
Name: count, dtype: int64

### Look at sample records

The next two cells display the first five rows of each version separately. Compare them: do their IDs, values, and missing entries match?

A sample helps you understand the data but does not check every row.

In [24]:
customers_raw.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [25]:
customers_saved.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### Compare the whole table

The following check compares every row and column. Tiny decimal differences caused by saving and rereading CSV files are allowed; text must match.

`pd.testing.assert_frame_equal()` raises an error if the tables differ unexpectedly. If it passes, the success message appears.

In [26]:
pd.testing.assert_frame_equal(customers_raw, customers_saved, check_exact=False, rtol=0.000000000001, atol=0.000000000001)
print("Passed: all table values match within the small decimal tolerance.")

Passed: all table values match within the small decimal tolerance.

### Your notes for customers

After reading the results, edit this Markdown cell in your own words:

- Raw and saved row/column counts:
- Missing values or duplicates noticed:
- What the sample rows show:
- Anything that needs more investigation:

Do not write "no issues" just because the files match. The original data may still contain issues.

## Check the order items table

### Read both files

`order_items_raw` holds the original table. `order_items_saved` holds the saved table.

If this cell finishes without an error, Pandas could read both files.

In [27]:
order_items_raw = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
order_items_saved = pd.read_csv("../data/processed/order_items.csv")
print("Both files loaded successfully.")

Both files loaded successfully.

### Check the size

`shape` shows `(rows, columns)`. The sizes should match because the script does not remove rows or columns.

In [28]:
print("Raw size:", order_items_raw.shape)
print("Saved size:", order_items_saved.shape)
print("Same size:", order_items_raw.shape == order_items_saved.shape)

Raw size: (112650, 7)
Saved size: (112650, 7)
Same size: True

### Check the column names

`columns` lists the column names. `equals()` checks whether both lists match, including their order. Expect `True`.

In [29]:
print("Raw columns:", order_items_raw.columns.tolist())
print("Saved columns:", order_items_saved.columns.tolist())
print("Same columns:", order_items_raw.columns.equals(order_items_saved.columns))

Raw columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
Saved columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
Same columns: True

### Check the data types

`dtypes` shows how Pandas stores each column. Text is shown as `str`, `string`, or `object`; whole numbers as `int64`; decimal numbers as `float64`.

The columns should have the same types in both tables. Matching types does not prove they suit every task: date text would need conversion before date calculations.

In [30]:
print("Raw types:")
print(order_items_raw.dtypes)
print("Saved types:")
print(order_items_saved.dtypes)
print("Same types:", order_items_raw.dtypes.equals(order_items_saved.dtypes))

Raw types:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object
Saved types:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object
Same types: True

### Check missing values

`isna().sum()` counts missing values in each column. The counts should stay the same because the script does not fill or remove missing values.

In [31]:
print("Raw missing values:")
print(order_items_raw.isna().sum())
print("Saved missing values:")
print(order_items_saved.isna().sum())
print("Same missing counts:", order_items_raw.isna().sum().equals(order_items_saved.isna().sum()))

Raw missing values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
Saved missing values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
Same missing counts: True

### Check duplicate rows

`duplicated().sum()` counts repeated complete rows. Repeated IDs alone are a different check.

The counts should stay the same. We have not decided to remove duplicates from these tables.

In [32]:
print("Raw duplicates:", order_items_raw.duplicated().sum())
print("Saved duplicates:", order_items_saved.duplicated().sum())
print("Same duplicate count:", order_items_raw.duplicated().sum() == order_items_saved.duplicated().sum())

Raw duplicates: 0

Saved duplicates: 0

Same duplicate count: True

### Check categories and distinct values

`nunique()` counts different non-missing values in each column. These counts should match.

We also inspect `order_item_id`. `value_counts(dropna=False)` counts each value, including missing values. The comparison checks the complete counts; the next cell displays at most ten values.

In [33]:
print("Same distinct counts:", order_items_raw.nunique().equals(order_items_saved.nunique()))
order_items_raw_counts = order_items_raw["order_item_id"].value_counts(dropna=False)
order_items_saved_counts = order_items_saved["order_item_id"].value_counts(dropna=False)
print("Same category counts:", order_items_raw_counts.equals(order_items_saved_counts))

Same distinct counts: True
Same category counts: True

In [34]:
order_items_saved_counts.head(10)

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
Name: count, dtype: int64

### Look at sample records

The next two cells display the first five rows of each version separately. Compare them: do their IDs, values, and missing entries match?

A sample helps you understand the data but does not check every row.

In [35]:
order_items_raw.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [36]:
order_items_saved.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

### Compare the whole table

The following check compares every row and column. Tiny decimal differences caused by saving and rereading CSV files are allowed; text must match.

`pd.testing.assert_frame_equal()` raises an error if the tables differ unexpectedly. If it passes, the success message appears.

In [37]:
pd.testing.assert_frame_equal(order_items_raw, order_items_saved, check_exact=False, rtol=0.000000000001, atol=0.000000000001)
print("Passed: all table values match within the small decimal tolerance.")

Passed: all table values match within the small decimal tolerance.

### Your notes for order items

After reading the results, edit this Markdown cell in your own words:

- Raw and saved row/column counts:
- Missing values or duplicates noticed:
- What the sample rows show:
- Anything that needs more investigation:

Do not write "no issues" just because the files match. The original data may still contain issues.

## Check the products table

### Read both files

`products_raw` holds the original table. `products_saved` holds the saved table.

If this cell finishes without an error, Pandas could read both files.

In [38]:
products_raw = pd.read_csv("../data/raw/olist_products_dataset.csv")
products_saved = pd.read_csv("../data/processed/products.csv")
print("Both files loaded successfully.")

Both files loaded successfully.

### Check the size

`shape` shows `(rows, columns)`. The sizes should match because the script does not remove rows or columns.

In [39]:
print("Raw size:", products_raw.shape)
print("Saved size:", products_saved.shape)
print("Same size:", products_raw.shape == products_saved.shape)

Raw size: (32951, 9)
Saved size: (32951, 9)
Same size: True

### Check the column names

`columns` lists the column names. `equals()` checks whether both lists match, including their order. Expect `True`.

In [40]:
print("Raw columns:", products_raw.columns.tolist())
print("Saved columns:", products_saved.columns.tolist())
print("Same columns:", products_raw.columns.equals(products_saved.columns))

Raw columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
Saved columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
Same columns: True

### Check the data types

`dtypes` shows how Pandas stores each column. Text is shown as `str`, `string`, or `object`; whole numbers as `int64`; decimal numbers as `float64`.

The columns should have the same types in both tables. Matching types does not prove they suit every task: date text would need conversion before date calculations.

In [41]:
print("Raw types:")
print(products_raw.dtypes)
print("Saved types:")
print(products_saved.dtypes)
print("Same types:", products_raw.dtypes.equals(products_saved.dtypes))

Raw types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
Saved types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
Same types: True

### Check missing values

`isna().sum()` counts missing values in each column. The counts should stay the same because the script does not fill or remove missing values.

In [42]:
print("Raw missing values:")
print(products_raw.isna().sum())
print("Saved missing values:")
print(products_saved.isna().sum())
print("Same missing counts:", products_raw.isna().sum().equals(products_saved.isna().sum()))

Raw missing values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
Saved missing values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
Same missing counts: True

### Check duplicate rows

`duplicated().sum()` counts repeated complete rows. Repeated IDs alone are a different check.

The counts should stay the same. We have not decided to remove duplicates from these tables.

In [43]:
print("Raw duplicates:", products_raw.duplicated().sum())
print("Saved duplicates:", products_saved.duplicated().sum())
print("Same duplicate count:", products_raw.duplicated().sum() == products_saved.duplicated().sum())

Raw duplicates: 0
Saved duplicates: 0

Same duplicate count: True

### Check categories and distinct values

`nunique()` counts different non-missing values in each column. These counts should match.

We also inspect `product_category_name`. `value_counts(dropna=False)` counts each value, including missing values. The comparison checks the complete counts; the next cell displays at most ten values.

In [44]:
print("Same distinct counts:", products_raw.nunique().equals(products_saved.nunique()))
products_raw_counts = products_raw["product_category_name"].value_counts(dropna=False)
products_saved_counts = products_saved["product_category_name"].value_counts(dropna=False)
print("Same category counts:", products_raw_counts.equals(products_saved_counts))

Same distinct counts: True
Same category counts: True

In [45]:
products_saved_counts.head(10)

product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

### Look at sample records

The next two cells display the first five rows of each version separately. Compare them: do their IDs, values, and missing entries match?

A sample helps you understand the data but does not check every row.

In [46]:
products_raw.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [47]:
products_saved.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

### Compare the whole table

The following check compares every row and column. Tiny decimal differences caused by saving and rereading CSV files are allowed; text must match.

`pd.testing.assert_frame_equal()` raises an error if the tables differ unexpectedly. If it passes, the success message appears.

In [48]:
pd.testing.assert_frame_equal(products_raw, products_saved, check_exact=False, rtol=0.000000000001, atol=0.000000000001)
print("Passed: all table values match within the small decimal tolerance.")

Passed: all table values match within the small decimal tolerance.

### Your notes for products

After reading the results, edit this Markdown cell in your own words:

- Raw and saved row/column counts:
- Missing values or duplicates noticed:
- What the sample rows show:
- Anything that needs more investigation:

Do not write "no issues" just because the files match. The original data may still contain issues.

## Check the order reviews table

### Read both files

`order_reviews_raw` holds the original table. `order_reviews_saved` holds the saved table.

If this cell finishes without an error, Pandas could read both files.

In [49]:
order_reviews_raw = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
order_reviews_saved = pd.read_csv("../data/processed/order_reviews.csv")
print("Both files loaded successfully.")

Both files loaded successfully.

### Check the size

`shape` shows `(rows, columns)`. The sizes should match because the script does not remove rows or columns.

In [50]:
print("Raw size:", order_reviews_raw.shape)
print("Saved size:", order_reviews_saved.shape)
print("Same size:", order_reviews_raw.shape == order_reviews_saved.shape)

Raw size: (99224, 7)
Saved size: (99224, 7)
Same size: True

### Check the column names

`columns` lists the column names. `equals()` checks whether both lists match, including their order. Expect `True`.

In [51]:
print("Raw columns:", order_reviews_raw.columns.tolist())
print("Saved columns:", order_reviews_saved.columns.tolist())
print("Same columns:", order_reviews_raw.columns.equals(order_reviews_saved.columns))

Raw columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
Saved columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
Same columns: True

### Check the data types

`dtypes` shows how Pandas stores each column. Text is shown as `str`, `string`, or `object`; whole numbers as `int64`; decimal numbers as `float64`.

The columns should have the same types in both tables. Matching types does not prove they suit every task: date text would need conversion before date calculations.

In [52]:
print("Raw types:")
print(order_reviews_raw.dtypes)
print("Saved types:")
print(order_reviews_saved.dtypes)
print("Same types:", order_reviews_raw.dtypes.equals(order_reviews_saved.dtypes))

Raw types:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object
Saved types:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object
Same types: True

### Check missing values

`isna().sum()` counts missing values in each column. The counts should stay the same because the script does not fill or remove missing values.

In [53]:
print("Raw missing values:")
print(order_reviews_raw.isna().sum())
print("Saved missing values:")
print(order_reviews_saved.isna().sum())
print("Same missing counts:", order_reviews_raw.isna().sum().equals(order_reviews_saved.isna().sum()))

Raw missing values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
Saved missing values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
Same missing counts: True

### Check duplicate rows

`duplicated().sum()` counts repeated complete rows. Repeated IDs alone are a different check.

The counts should stay the same. We have not decided to remove duplicates from these tables.

In [54]:
print("Raw duplicates:", order_reviews_raw.duplicated().sum())
print("Saved duplicates:", order_reviews_saved.duplicated().sum())
print("Same duplicate count:", order_reviews_raw.duplicated().sum() == order_reviews_saved.duplicated().sum())

Raw duplicates: 0

Saved duplicates: 0

Same duplicate count: True

### Check categories and distinct values

`nunique()` counts different non-missing values in each column. These counts should match.

We also inspect `review_score`. `value_counts(dropna=False)` counts each value, including missing values. The comparison checks the complete counts; the next cell displays at most ten values.

In [55]:
print("Same distinct counts:", order_reviews_raw.nunique().equals(order_reviews_saved.nunique()))
order_reviews_raw_counts = order_reviews_raw["review_score"].value_counts(dropna=False)
order_reviews_saved_counts = order_reviews_saved["review_score"].value_counts(dropna=False)
print("Same category counts:", order_reviews_raw_counts.equals(order_reviews_saved_counts))

Same distinct counts: True
Same category counts: True

In [56]:
order_reviews_saved_counts.head(10)

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

### Look at sample records

The next two cells display the first five rows of each version separately. Compare them: do their IDs, values, and missing entries match?

A sample helps you understand the data but does not check every row.

In [57]:
order_reviews_raw.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [58]:
order_reviews_saved.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

### Compare the whole table

The following check compares every row and column. Tiny decimal differences caused by saving and rereading CSV files are allowed; text must match.

`pd.testing.assert_frame_equal()` raises an error if the tables differ unexpectedly. If it passes, the success message appears.

In [59]:
pd.testing.assert_frame_equal(order_reviews_raw, order_reviews_saved, check_exact=False, rtol=0.000000000001, atol=0.000000000001)
print("Passed: all table values match within the small decimal tolerance.")

Passed: all table values match within the small decimal tolerance.

### Your notes for order reviews

After reading the results, edit this Markdown cell in your own words:

- Raw and saved row/column counts:
- Missing values or duplicates noticed:
- What the sample rows show:
- Anything that needs more investigation:

Do not write "no issues" just because the files match. The original data may still contain issues.

## Final check: customer ZIP-code text

`equals()` compares every original prefix with its saved version. This includes any leading zeros. Expect `True`.

In [60]:
print("All ZIP-code prefixes preserved:", customers_raw["customer_zip_code_prefix"].equals(customers_saved["customer_zip_code_prefix"]))

All ZIP-code prefixes preserved: True

## What the results mean

If all checks pass, the processing script preserved the tables as intended, and the raw files stayed unchanged during this run.

This does **not** mean that the data is fully cleaned or that every business rule is satisfied. Your current script mostly reads and saves files. Investigate missing values, dates, and repeated identifiers before deciding on further changes.

Record your findings in `docs/observation.md`. If you later change the processing rules, update the expected results here too.